#
# Hashcraft Proxy configuration
# Made by LoRy24
#
settings:

  #
  # Enable debug messages
  #
  debug: true

  #
  # The options about the server list pint. In this section you can edit options such as the Message of the day, the
  # server brand and the maximum amount of players.
  #
  serverListPing:

    #
    # The message of the day. This value will be displayed as message of when a player pings the server.
    #
    # Value: A string with colors (Written with the 'ยง' or with the '&')
    #
    messageOfTheDay: "&7Just another &6Hashcraft Proxy"

    #
    # The maximum amount of players that can be connected to the proxy (Not a limit but just a shown value)
    #
    # Value: An integer
    #
    maxPlayersAmount: 200

  #
  # This value is the server where the Proxy tries to send the players when they join the network.
  #
  onJoinServer: "lobby"

  #
  # The servers that are going to get registered in the Proxy's sub-servers register. These servers should have the
  # 'bungeecord' option enabled.
  #
  servers:

    #
    # This is a sample server
    #
    lobby:
      host: "127.0.0.1"
      port: 25565

  #
  # The host where the proxy should start listening on
  #
  # Value: IPv4 address
  #
  host: "127.0.0.1"

  #
  # The port where to listen the server.
  #
  # Value: an unsigned short (0-65535)
  #
  port: 25565

  #
  # This option will define if the proxy should send the message that says "/address:port has pinged." everytime someone
  # pings the server.
  #
  # Value: Boolean (stored in a string: true or false)
  #
  sendPingMessage: true